#!/bin/bash

set -e

#Mettre à jour le miroir Debian
reprepro -Vb /home/kaisen/deb/ --noskipold --export=never update

#Charger les paquets de packages vers devel. De devel vers rolling. De rolling-snapshot vers rolling.
reprepro -Vb /home/kaisen/deb pull
reprepro -Vb /home/kaisen/deb pull
reprepro -Vb /home/kaisen/deb pull
