#!/bin/bash

set -e

if [[ "$EUID" -ne 0 ]]; then
	echo "Run this script as root."
	exit 1
fi

#Update Debian mirror
reprepro -Vb /srv/deb/ --noskipold --export=never update

#Pull kaisen-rolling-snapshot packages to kaisen-rolling. Pull kaisen-packages packages to kaisen-devel. Pull kaisen-devel packages to kaisen-rolling.
reprepro -Vb /srv/deb pull
