#!/bin/bash

set -e

#Pour la suppression de paquets en dehors du noyau Linux qui est versionné différemment des autres logiciels,
#Privilégier une FilterList dans le fichier conf/updates.

#Mettre à jour le référentiel de Debian
reprepro -Vb /home/kaisen/deb/ update
#Charger les paquets de Kaisen depuis le référentiel de développement (kaisen-devel)
reprepro -Vb /home/kaisen/deb pull kaisen-rolling
